apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque #user-defined data so opaque
data:
  username: "YWRtaW4=" # encoded value of admin. cmd: echo -n "admin" | base64
  password: "YWRtaW4xMjM=" # encoded value of admin123. cmd: echo -n "admin" | base64
